id: CG-AL-H012
prompt_template: code-gen.md
fix_template: bugfix.md
max_attempts: 2
description: >-
  Create an AL control add-in named "CG Data Visualizer" that:

  1. Has RequestedHeight = 400 and MinimumHeight = 200
  2. Has RequestedWidth = 600 and MinimumWidth = 300
  3. Sets VerticalStretch, VerticalShrink, HorizontalStretch, HorizontalShrink all to true
  4. Declares a Scripts property referencing 'Resources/DataVisualizer/js/main.js'
  5. Declares a StartupScript property referencing 'Resources/DataVisualizer/js/startup.js'
  6. Declares a StyleSheets property referencing 'Resources/DataVisualizer/css/styles.css'
  7. Has an event "ControlReady" with no parameters
  8. Has an event "DataPointSelected" with a JsonObject parameter named "Point"
  9. Has a procedure "Initialize" with no parameters
  10. Has a procedure "UpdateData" with a JsonArray parameter named "Data"
  11. Has a procedure "SetTitle" with a Text parameter named "Title"

expected:
  compile: true
  testApp: tests/al/hard/CG-AL-H012.Test.al
metrics:
  - compile_pass
  - tests_pass
  - pass_attempt
